// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Windows_Storage_Pickers_1_H
#define WINRT_Windows_Storage_Pickers_1_H
#include "winrt/impl/Windows.Storage.Pickers.0.h"
WINRT_EXPORT namespace winrt::Windows::Storage::Pickers
{
    struct __declspec(empty_bases) IFileOpenPicker :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileOpenPicker>
    {
        IFileOpenPicker(std::nullptr_t = nullptr) noexcept {}
        IFileOpenPicker(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileOpenPicker2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileOpenPicker2>,
        impl::require<winrt::Windows::Storage::Pickers::IFileOpenPicker2, winrt::Windows::Storage::Pickers::IFileOpenPicker>
    {
        IFileOpenPicker2(std::nullptr_t = nullptr) noexcept {}
        IFileOpenPicker2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileOpenPickerStatics :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileOpenPickerStatics>
    {
        IFileOpenPickerStatics(std::nullptr_t = nullptr) noexcept {}
        IFileOpenPickerStatics(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileOpenPickerWithOperationId :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileOpenPickerWithOperationId>
    {
        IFileOpenPickerWithOperationId(std::nullptr_t = nullptr) noexcept {}
        IFileOpenPickerWithOperationId(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileSavePicker :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileSavePicker>
    {
        IFileSavePicker(std::nullptr_t = nullptr) noexcept {}
        IFileSavePicker(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileSavePicker2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileSavePicker2>,
        impl::require<winrt::Windows::Storage::Pickers::IFileSavePicker2, winrt::Windows::Storage::Pickers::IFileSavePicker>
    {
        IFileSavePicker2(std::nullptr_t = nullptr) noexcept {}
        IFileSavePicker2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFileSavePicker3 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFileSavePicker3>,
        impl::require<winrt::Windows::Storage::Pickers::IFileSavePicker3, winrt::Windows::Storage::Pickers::IFileSavePicker>
    {
        IFileSavePicker3(std::nullptr_t = nullptr) noexcept {}
        IFileSavePicker3(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFolderPicker :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFolderPicker>
    {
        IFolderPicker(std::nullptr_t = nullptr) noexcept {}
        IFolderPicker(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
    struct __declspec(empty_bases) IFolderPicker2 :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IFolderPicker2>,
        impl::require<winrt::Windows::Storage::Pickers::IFolderPicker2, winrt::Windows::Storage::Pickers::IFolderPicker>
    {
        IFolderPicker2(std::nullptr_t = nullptr) noexcept {}
        IFolderPicker2(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
